## Data PreProcessing

In [2]:
'''import kagglehub

# Download latest version
path = kagglehub.dataset_download("rounakbanik/the-movies-dataset")

print("Path to dataset files:", path)'''

'import kagglehub\n\n# Download latest version\npath = kagglehub.dataset_download("rounakbanik/the-movies-dataset")\n\nprint("Path to dataset files:", path)'

In [5]:
import pandas as pd
path = 'C:\\Users\\omsaw\\Project\\DataSet'
movies_metadata = pd.read_csv(path + '/movies_metadata.csv')
movies_metadata.head()

C:\Users\omsaw\AppData\Local\Temp\ipykernel_16296\3385698371.py:3: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  movies_metadata = pd.read_csv(path + '/movies_metadata.csv')

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [6]:
credits = pd.read_csv(path + '/credits.csv')
credits.head()

,cast,crew,id
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602
3,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862

In [7]:
links = pd.read_csv(path + '/links.csv')
links.head()

   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

In [8]:
keywords = pd.read_csv(path + '/keywords.csv')
keywords.head()

      id                                           keywords
0    862  [{'id': 931, 'name': 'jealousy'}, {'id': 4290,...
1   8844  [{'id': 10090, 'name': 'board game'}, {'id': 1...
2  15602  [{'id': 1495, 'name': 'fishing'}, {'id': 12392...
3  31357  [{'id': 818, 'name': 'based on novel'}, {'id':...
4  11862  [{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...

In [9]:
import numpy as np

# Convert 'id' columns to numeric, coercing errors to NaN
movies_metadata['id'] = pd.to_numeric(movies_metadata['id'], errors='coerce')
credits['id'] = pd.to_numeric(credits['id'], errors='coerce')
links['tmdbId'] = pd.to_numeric(links['tmdbId'], errors='coerce')

# Drop rows where 'id' or 'tmdbId' became NaN after conversion, as these cannot be merged
movies_metadata.dropna(subset=['id'], inplace=True)
credits.dropna(subset=['id'], inplace=True)
links.dropna(subset=['tmdbId'], inplace=True)

# Ensure 'id' columns are integers after handling NaNs for cleaner merging
movies_metadata['id'] = movies_metadata['id'].astype(int)
credits['id'] = credits['id'].astype(int)
links['tmdbId'] = links['tmdbId'].astype(int)

print('Data types for merge keys after cleaning:')
print(f"movies_metadata['id'] dtype: {movies_metadata['id'].dtype}")
print(f"credits['id'] dtype: {credits['id'].dtype}")
print(f"links['tmdbId'] dtype: {links['tmdbId'].dtype}")

Data types for merge keys after cleaning:
movies_metadata['id'] dtype: int32
credits['id'] dtype: int32
links['tmdbId'] dtype: int32

Now that the ID columns are cleaned and typed correctly, I will merge `movies_metadata` with `credits`, and then the resulting dataframe with `links`.

In [10]:
# Merge movies_metadata and credits
merged_df = pd.merge(movies_metadata, credits, on='id', how='inner')

# Merge the result with links using 'id' from merged_df and 'tmdbId' from links
merged_df = pd.merge(merged_df, links, left_on='id', right_on='tmdbId', how='inner')

# Merge the result with keywords
merged_df = pd.merge(merged_df, keywords, on='id', how='inner')

# Drop redundant ID columns from the links table
merged_df.drop(columns=['tmdbId', 'movieId'], inplace=True)

print('Shape of the merged dataframe:', merged_df.shape)
display(merged_df.head())

Shape of the merged dataframe: (46910, 28)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,status,tagline,title,video,vote_average,vote_count,cast,crew,imdbId,keywords
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,Released,NaN,Toy Story,False,7.7,5415.0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",114709,"[{'id': 931, 'name': 'jealousy'}, {'id': 4290,..."
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",113497,"[{'id': 10090, 'name': 'board game'}, {'id': 1..."
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",113228,"[{'id': 1495, 'name': 'fishing'}, {'id': 12392..."
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",114885,"[{'id': 818, 'name': 'based on novel'}, {'id':..."
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",113041,"[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n..."

In [11]:
columns_to_keep = ['genres', 'id', 'keywords', 'title', 'overview', 'cast', 'crew', 'tagline']
movies = merged_df[columns_to_keep].copy()

print('Shape of the filtered dataframe:', movies.shape)
display(movies.head())

Shape of the filtered dataframe: (46910, 8)

,genres,id,keywords,title,overview,cast,crew,tagline
0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",862,"[{'id': 931, 'name': 'jealousy'}, {'id': 4290,...",Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",NaN
1,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",8844,"[{'id': 10090, 'name': 'board game'}, {'id': 1...",Jumanji,When siblings Judy and Peter discover an encha...,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",Roll the dice and unleash the excitement!
2,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",15602,"[{'id': 1495, 'name': 'fishing'}, {'id': 12392...",Grumpier Old Men,A family wedding reignites the ancient feud be...,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",Still Yelling. Still Fighting. Still Ready for...
3,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",31357,"[{'id': 818, 'name': 'based on novel'}, {'id':...",Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",Friends are the people who let you be yourself...
4,"[{'id': 35, 'name': 'Comedy'}]",11862,"[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...",Father of the Bride Part II,Just when George Banks has recovered from his ...,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",Just When His World Is Back To Normal... He's ...

In [12]:
import ast

#function to covert
def convert(obj):
  L = []
  for i in ast.literal_eval(obj):
    L.append(i['name'])
  return L

In [13]:
movies['genres'] = movies['genres'].apply(convert)

In [14]:
movies['keywords'] = movies['keywords'].apply(convert)

In [15]:
def convert3(obj):
  L = []
  counter=0
  for i in ast.literal_eval(obj):
    if counter != 3:
      L.append(i['name'])
      counter+=1
    else:
      break
  return L

In [16]:
movies['cast'] = movies['cast'].apply(convert3)
movies.head()

,genres,id,keywords,title,overview,cast,crew,tagline
0,"[Animation, Comedy, Family]",862,"[jealousy, toy, boy, friendship, friends, riva...",Toy Story,"Led by Woody, Andy's toys live happily in his ...","[Tom Hanks, Tim Allen, Don Rickles]","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",NaN
1,"[Adventure, Fantasy, Family]",8844,"[board game, disappearance, based on children'...",Jumanji,When siblings Judy and Peter discover an encha...,"[Robin Williams, Jonathan Hyde, Kirsten Dunst]","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",Roll the dice and unleash the excitement!
2,"[Romance, Comedy]",15602,"[fishing, best friend, duringcreditsstinger, o...",Grumpier Old Men,A family wedding reignites the ancient feud be...,"[Walter Matthau, Jack Lemmon, Ann-Margret]","[{'credit_id': '52fe466a9251416c75077a89', 'de...",Still Yelling. Still Fighting. Still Ready for...
3,"[Comedy, Drama, Romance]",31357,"[based on novel, interracial relationship, sin...",Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[Whitney Houston, Angela Bassett, Loretta Devine]","[{'credit_id': '52fe44779251416c91011acb', 'de...",Friends are the people who let you be yourself...
4,[Comedy],11862,"[baby, midlife crisis, confidence, aging, daug...",Father of the Bride Part II,Just when George Banks has recovered from his ...,"[Steve Martin, Diane Keaton, Martin Short]","[{'credit_id': '52fe44959251416c75039ed7', 'de...",Just When His World Is Back To Normal... He's ...

In [17]:
def fetch_director(obj):
  L = []
  for i in ast.literal_eval(obj):
    if i['job'] == 'Director':
      L.append(i['name'])
      break
  return L

In [18]:
movies['crew']= movies['crew'].apply(fetch_director)

In [19]:
movies.head()

,genres,id,keywords,title,overview,cast,crew,tagline
0,"[Animation, Comedy, Family]",862,"[jealousy, toy, boy, friendship, friends, riva...",Toy Story,"Led by Woody, Andy's toys live happily in his ...","[Tom Hanks, Tim Allen, Don Rickles]",[John Lasseter],NaN
1,"[Adventure, Fantasy, Family]",8844,"[board game, disappearance, based on children'...",Jumanji,When siblings Judy and Peter discover an encha...,"[Robin Williams, Jonathan Hyde, Kirsten Dunst]",[Joe Johnston],Roll the dice and unleash the excitement!
2,"[Romance, Comedy]",15602,"[fishing, best friend, duringcreditsstinger, o...",Grumpier Old Men,A family wedding reignites the ancient feud be...,"[Walter Matthau, Jack Lemmon, Ann-Margret]",[Howard Deutch],Still Yelling. Still Fighting. Still Ready for...
3,"[Comedy, Drama, Romance]",31357,"[based on novel, interracial relationship, sin...",Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[Whitney Houston, Angela Bassett, Loretta Devine]",[Forest Whitaker],Friends are the people who let you be yourself...
4,[Comedy],11862,"[baby, midlife crisis, confidence, aging, daug...",Father of the Bride Part II,Just when George Banks has recovered from his ...,"[Steve Martin, Diane Keaton, Martin Short]",[Charles Shyer],Just When His World Is Back To Normal... He's ...

In [20]:
movies['overview'][0]

"Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences."

In [21]:
movies['overview'] = movies['overview'].astype(str).apply(lambda x:x.split())

In [22]:
movies.isnull().sum()

genres          0
id              0
keywords        0
title           4
overview        0
cast            0
crew            0
tagline     26001
dtype: int64

In [23]:
movies = movies.drop('tagline', axis=1)

In [24]:
movies.isnull().sum()

genres      0
id          0
keywords    0
title       4
overview    0
cast        0
crew        0
dtype: int64

In [25]:
movies = movies.dropna(subset=['overview'])

In [26]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [27]:
movies.head()

,genres,id,keywords,title,overview,cast,crew
0,"[Animation, Comedy, Family]",862,"[jealousy, toy, boy, friendship, friends, riva...",Toy Story,"[Led, by, Woody,, Andy's, toys, live, happily,...","[TomHanks, TimAllen, DonRickles]",[JohnLasseter]
1,"[Adventure, Fantasy, Family]",8844,"[boardgame, disappearance, basedonchildren'sbo...",Jumanji,"[When, siblings, Judy, and, Peter, discover, a...","[RobinWilliams, JonathanHyde, KirstenDunst]",[JoeJohnston]
2,"[Romance, Comedy]",15602,"[fishing, bestfriend, duringcreditsstinger, ol...",Grumpier Old Men,"[A, family, wedding, reignites, the, ancient, ...","[WalterMatthau, JackLemmon, Ann-Margret]",[HowardDeutch]
3,"[Comedy, Drama, Romance]",31357,"[basedonnovel, interracialrelationship, single...",Waiting to Exhale,"[Cheated, on,, mistreated, and, stepped, on,, ...","[WhitneyHouston, AngelaBassett, LorettaDevine]",[ForestWhitaker]
4,[Comedy],11862,"[baby, midlifecrisis, confidence, aging, daugh...",Father of the Bride Part II,"[Just, when, George, Banks, has, recovered, fr...","[SteveMartin, DianeKeaton, MartinShort]",[CharlesShyer]

In [28]:
movies['tags']=movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']
movies.head()

,genres,id,keywords,title,overview,cast,crew,tags
0,"[Animation, Comedy, Family]",862,"[jealousy, toy, boy, friendship, friends, riva...",Toy Story,"[Led, by, Woody,, Andy's, toys, live, happily,...","[TomHanks, TimAllen, DonRickles]",[JohnLasseter],"[Led, by, Woody,, Andy's, toys, live, happily,..."
1,"[Adventure, Fantasy, Family]",8844,"[boardgame, disappearance, basedonchildren'sbo...",Jumanji,"[When, siblings, Judy, and, Peter, discover, a...","[RobinWilliams, JonathanHyde, KirstenDunst]",[JoeJohnston],"[When, siblings, Judy, and, Peter, discover, a..."
2,"[Romance, Comedy]",15602,"[fishing, bestfriend, duringcreditsstinger, ol...",Grumpier Old Men,"[A, family, wedding, reignites, the, ancient, ...","[WalterMatthau, JackLemmon, Ann-Margret]",[HowardDeutch],"[A, family, wedding, reignites, the, ancient, ..."
3,"[Comedy, Drama, Romance]",31357,"[basedonnovel, interracialrelationship, single...",Waiting to Exhale,"[Cheated, on,, mistreated, and, stepped, on,, ...","[WhitneyHouston, AngelaBassett, LorettaDevine]",[ForestWhitaker],"[Cheated, on,, mistreated, and, stepped, on,, ..."
4,[Comedy],11862,"[baby, midlifecrisis, confidence, aging, daugh...",Father of the Bride Part II,"[Just, when, George, Banks, has, recovered, fr...","[SteveMartin, DianeKeaton, MartinShort]",[CharlesShyer],"[Just, when, George, Banks, has, recovered, fr..."

In [29]:
df = movies[['id','title','tags']]
df.head()

,id,title,tags
0,862,Toy Story,"[Led, by, Woody,, Andy's, toys, live, happily,..."
1,8844,Jumanji,"[When, siblings, Judy, and, Peter, discover, a..."
2,15602,Grumpier Old Men,"[A, family, wedding, reignites, the, ancient, ..."
3,31357,Waiting to Exhale,"[Cheated, on,, mistreated, and, stepped, on,, ..."
4,11862,Father of the Bride Part II,"[Just, when, George, Banks, has, recovered, fr..."

In [30]:
df['tags']=df['tags'].apply(lambda x:" ".join(x))
df.head()

C:\Users\omsaw\AppData\Local\Temp\ipykernel_16296\526279989.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tags']=df['tags'].apply(lambda x:" ".join(x))

,id,title,tags
0,862,Toy Story,"Led by Woody, Andy's toys live happily in his ..."
1,8844,Jumanji,When siblings Judy and Peter discover an encha...
2,15602,Grumpier Old Men,A family wedding reignites the ancient feud be...
3,31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom..."
4,11862,Father of the Bride Part II,Just when George Banks has recovered from his ...

In [31]:
df['tags'][0]

"Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences. Animation Comedy Family jealousy toy boy friendship friends rivalry boynextdoor newtoy toycomestolife TomHanks TimAllen DonRickles JohnLasseter"

In [32]:
df['tags']=df['tags'].apply(lambda x:x.lower())
df.head()

C:\Users\omsaw\AppData\Local\Temp\ipykernel_16296\3887520198.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tags']=df['tags'].apply(lambda x:x.lower())

,id,title,tags
0,862,Toy Story,"led by woody, andy's toys live happily in his ..."
1,8844,Jumanji,when siblings judy and peter discover an encha...
2,15602,Grumpier Old Men,a family wedding reignites the ancient feud be...
3,31357,Waiting to Exhale,"cheated on, mistreated and stepped on, the wom..."
4,11862,Father of the Bride Part II,just when george banks has recovered from his ...

In [33]:
df.shape

(46910, 3)

## Vectorization

In [35]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=50000,ngram_range=(1,2), stop_words='english')
vectorized_data = tfidf.fit_transform(df['tags'])

print("Shape of vectorized data:", vectorized_data.shape)

Shape of vectorized data: (46910, 50000)

In [36]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vectorized_data)

In [37]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(3032, 0.46326479172455914),
 (15586, 0.44659690501744526),
 (24891, 0.2497345073839155),
 (10413, 0.22660135468315828),
 (24204, 0.202938037085202)]

In [38]:
def recommend(movie):
  movie_index = df[df['title'] == movie].index[0]
  distances = similarity[movie_index]
  movie_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]

  for i in movie_list:
    print(df.iloc[i[0]].title)

In [39]:
import pickle
pickle.dump(df.to_dict(),open('movies_dict.pkl','wb'))

In [40]:
pickle.dump(similarity,open('similarity.pkl','wb'))